### ISSUE TITLE
Study on the correlation between big company and mental disorder

### ISSUE THREAD

**Issue by benjaminsihi** [ablepie/info201au-final-project#4]
It's the second question we proposed in the project proposal. To study the correlation between the size of the company and the likelihood of its employees getting the mental disorder. 
   We believe there is a positive linear relationship between the number of employees in the company the possibility of getting a mental disorder.
   To study this question we will process the dataset from 2016, and 2017 to reach a more convincing conclusion.

**Comment by chenxd2** [comment]
Ben finally study the regression with working location and mental disorder.
