### ISSUE TITLE
Pre-process on textual/qualitative input. 

### ISSUE THREAD

**Issue by benjaminsihi** [ablepie/info201au-final-project#5]
The raw dataset contains textual input and qualitative variables that are hard to categorize and thus visualize. What Benjamin needs to do is process those inputs and reformat those inputs in quantitative measurement. 
   For instance, the question "_If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave_?" is measured on the scale of 4, very difficult, somewhat difficult, somewhat easy, very easy and I don't know. In this scenario, those inputs can be easily transformed to the scale of 1-4 and I don't know would be considered as a NULL input.

**Comment by chenxd2** [comment]
Ben and april solved.
